// react/src/components/Contact.tsx
// src/components/Contact.tsx
import type { FC } from 'react';
import type { ContactSection as ContactSectionData } from '../types';
import { SanityPortableText } from '../sanity/SanityPortableText';
import { Button } from './ui/Button';

type ContactProps = {
  section: ContactSectionData;
};

export const Contact: FC<ContactProps> = ({ section }) => {
  const { title, body, ctas = [], emailAddress, emailLabel } = section;

  const emailHref = emailAddress ? `mailto:${emailAddress}` : undefined;
  const hasCtas = Boolean(emailHref || ctas.length);

  return (
    <section id="contact">
      <div>
        <div className="grid grid-cols-1 gap-m items-start md:grid-cols-2">
          <div className="card card--fx">
            {title && <h2 className="h2 mb-s leading-0">{title}</h2>}

            <SanityPortableText value={body} />

            {hasCtas && (
              <div className="mt-m flex flex-wrap gap-s">
                {emailHref && (
                  <Button
                    href={emailHref}
                    variant="primary"
                  >
                    {emailLabel || 'Email me'}
                  </Button>
                )}

                {ctas.map(({ label, href, style }, index) => {
                  if (!href || !label) return null;
                  const variant = style === 'primary' ? 'primary' : 'default';

                  return (
                    <Button
                      key={`${label}-${index}`}
                      href={href}
                      variant={variant}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      {label}
                    </Button>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Contact;

// vue/src/components/Contact.vue
<template>
  <section id="contact">
    <div class="container-regular">
      <div class="grid grid-cols-1 gap-m items-start md:grid-cols-2">
        <div class="card card--fx">
          <h2 v-if="section.title" class="h2 mb-s leading-0">{{ section.title }}</h2>

          <PortableText :value="section.body" />

          <div v-if="hasCtas" class="mt-m flex flex-wrap gap-s">
            <Button :href="emailHref" variant="primary" :disabled="!emailHref">
              {{ section.emailLabel || 'Email me' }}
            </Button>

            <template v-for="(cta, index) in section.ctas" :key="`${cta.label}-${index}`">
              <Button
                v-if="cta.href && cta.label"
                :href="cta.href"
                :variant="cta.style === 'primary' ? 'primary' : 'default'"
                target="_blank"
                rel="noopener noreferrer"
              >
                {{ cta.label }}
              </Button>
            </template>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { ContactSection } from '../types'
import Button from './ui/Button.vue'
import PortableText from './ui/PortableText.vue'

const props = defineProps<{
  section: ContactSection
}>()

const emailHref = computed(() =>
  props.section.emailAddress ? `mailto:${props.section.emailAddress}` : undefined
)

const hasCtas = computed(() => Boolean(props.section.emailLabel || props.section.emailAddress || props.section.ctas?.length))
</script>
