// react/src/components/DesktopNav.tsx
import type { FC } from 'react';
import { Link } from './ui/Link';

export type NavItem = {
  label: string;
  href: string;
};

interface DesktopNavProps {
  label: string;
  items: NavItem[];
}

export const DesktopNav: FC<DesktopNavProps> = ({
  label,
  items,
}) => {
  if (!items.length) return null;

  return (
    <nav aria-label={label} className="hidden items-center gap-l md:flex">
      {items.map((item) => (
        <Link key={item.href ?? item.label} href={item.href}>
          {item.label}
        </Link>
      ))}
    </nav>
  );
};

// vue/src/components/DesktopNav.vue
<template>
  <nav v-if="items.length" :aria-label="label" class="hidden items-center gap-l md:flex">
    <Link v-for="item in items" :key="item.href ?? item.label" :href="item.href">
      {{ item.label }}
    </Link>
  </nav>
</template>

<script setup lang="ts">
import Link from './ui/Link.vue'
import type { NavItem } from '../types'

defineProps<{
  label: string
  items: NavItem[]
}>()
</script>
