// react/src/components/Sections.tsx
import type { FC } from 'react';
import type {
  HomePage,
  HomeSection,
  HeroSection,
  StringsDoc,
} from '../types';
import { useSanityData } from '../sanity/useSanityData';
import { Hero } from './Hero';

type SanityContextShape = {
  home?: HomePage | null;
  strings?: StringsDoc | null;
};

const renderSection = (
  section: HomeSection,
  index: number,
  strings?: StringsDoc | null
) => {
  switch (section._type) {
    case 'heroSection':
      return (
        <Hero
          key={`hero-${index}`}
          hero={section as HeroSection}
        />
      );

    // TODO: Add other sections here
    // case 'aboutSection':
    //   return <About key={`about-${index}`} section={section as AboutSection} strings={strings} />;
    // case 'workLogosGridSection':
    //   return <WorkLogosGrid key={`work-${index}`} section={section as WorkLogosGridSection} />;
    // case 'skillsSection':
    //   return <Skills key={`skills-${index}`} section={section as SkillsSection} />;
    // case 'stackSection':
    //   return <Stack key={`stack-${index}`} section={section as StackSection} />;
    // case 'contactSection':
    //   return <Contact key={`contact-${index}`} section={section as ContactSection} strings={strings} />;

    default: {
      if (import.meta.env.DEV) {

        console.warn('[CMS] Unmapped section type:', section._type);
      }
      return null;
    }
  }
};

export const Sections: FC = () => {
  const { home, strings } = useSanityData() as SanityContextShape;

  const sections = home?.sections ?? [];
  if (!sections.length) return null;


  // Build sections from Sanity
  return (
    <>
      {sections.map((section, index) =>
        renderSection(section, index, strings)
      )}
    </>
  );
};

export default Sections;

// vue/src/components/Sections.vue
<template>
  <template v-for="(section, index) in sections" :key="`${section._type}-${index}`">

    <Hero v-if="section._type === 'heroSection'" :section="(section as HeroSection)" />

    <About v-else-if="section._type === 'aboutSection'" :section="(section as AboutSection)" />

    <WorkLogosGrid
      v-else-if="section._type === 'workLogosGridSection'"
      :section="(section as WorkLogosGridSection)"
      :strings="strings"
    />

    <Skills v-else-if="section._type === 'skillsSection'" :section="(section as SkillsSection)" />

    <Stack
      v-else-if="section._type === 'stackSection'"
      :section="(section as StackSection)"
      :strings="strings"
    />

    <Contact v-else-if="section._type === 'contactSection'" :section="(section as ContactSection)" />

  </template>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useSanityData } from '../composables/useSanityData'
import Hero from './Hero.vue'
import About from './About.vue'
import WorkLogosGrid from './WorkLogosGrid.vue'
import Skills from './Skills.vue'
import Stack from './Stack.vue'
import Contact from './Contact.vue'
import type {
  HeroSection,
  AboutSection,
  WorkLogosGridSection,
  SkillsSection,
  StackSection,
  ContactSection,
} from '../types'

type KnownSection =
  | HeroSection
  | AboutSection
  | WorkLogosGridSection
  | SkillsSection
  | StackSection
  | ContactSection
  | { _type: string }

const { data } = useSanityData()

const sections = computed<KnownSection[]>(() => (data.value?.home?.sections as KnownSection[]) ?? [])
const strings = computed(() => data.value?.strings ?? null)
</script>
