// vue/src/components/About.vue
<template>
  <section id="about">
    <div class="container-regular">
      <div class="grid grid-cols-1 gap-m md:grid-cols-2 md:gap-l">
        <!-- Left card: main copy -->
        <div>
          <div class="card card--fx">
            <h2 v-if="section.title" class="h2 mb-m">{{ section.title }}</h2>
            <PortableText :value="section.body" />
          </div>
        </div>

        <!-- Right card: subtitle + bullets -->
        <div>
          <div class="card card--fx">
            <h3 v-if="section.subtitle" class="h2 badge--mono mb-m">
              {{ section.subtitle }}
            </h3>

            <ul v-if="section.bullets?.length" class="card__list">
              <li v-for="(text, index) in section.bullets" :key="`${text}-${index}`">
                {{ text }}
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import type { AboutSection } from '../types'
import PortableText from './ui/PortableText.vue'

defineProps<{
  section: AboutSection
}>()
</script>

// react/src/components/About.tsx
import type { FC } from 'react';
import type { AboutSection as AboutSectionData } from '../types';
import { SanityPortableText } from '../sanity/SanityPortableText';

type AboutProps = {
  section: AboutSectionData;
};

export const About: FC<AboutProps> = ({ section }) => {
  const { title, body, subtitle, bullets = [] } = section;
  const hasBullets = bullets.length > 0;

  return (
    <section id="about">
      <div>
        <div className="grid grid-cols-1 gap-m md:grid-cols-2 md:gap-m">
          {/* Left card: main copy */}
          <div>
            <div className="card card--fx">
              {title && <h2 className="h2 mb-s">{title}</h2>}

              <SanityPortableText value={body} />
            </div>
          </div>

          {/* Right card: subtitle + bullets */}
          <div>
            <div className="card card--fx">
              {subtitle && (
                <h3 className="h2 badge--mono mb-s">
                  {subtitle}
                </h3>
              )}

              {hasBullets && (
                <ul className="card__list">
                  {bullets.map((text, index) => (
                    <li key={`${text}-${index}`}>{text}</li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default About;
