// vue/src/components/Footer.vue
<template>
  <footer class="py-l">
    <div class="container-regular grid grid-cols-1 gap-2xs">
      <p v-if="builtWithText" class="text-muted text-base leading-0 tracking-1 m-0">
        {{ builtWithText }}
      </p>
      <p class="text-accent text-sm m-0">© {{ year }} {{ siteName }}</p>
    </div>
  </footer>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useSanityData } from '../composables/useSanityData'
import { getBuiltWithFromSections } from '../utils/stackHelpers'
import type { HomeSection } from '../types'

const { data } = useSanityData()

const siteName = computed(() => data.value?.settings?.siteName ?? '')
const builtWithText = computed(() =>
  getBuiltWithFromSections(data.value?.home?.sections as HomeSection[] | null)
)
const year = new Date().getFullYear()
</script>

// react/src/components/Footer.tsx
// src/components/Footer.tsx
import type { FC } from 'react';
import type { HomePage, SiteSettings } from '../types';
import { useSanityData } from '../sanity/useSanityData';
import { getBuiltWithFromSections } from '../utils/stackHelpers';

type SanityContextShape = {
  home?: HomePage | null;
  settings?: SiteSettings | null;
};

export const Footer: FC = () => {
  const { home, settings } = useSanityData() as SanityContextShape;

  const title = settings?.siteName ?? '';
  const builtWithText = getBuiltWithFromSections(home?.sections ?? []) ?? '';

  const year = new Date().getFullYear();

  return (
    <footer className="py-l">
      <div className="container-regular grid grid-cols-1 gap-2xs">
        {builtWithText && (
          <p className="text-muted text-base leading-0 tracking-1 m-0">
            {builtWithText}
          </p>
        )}
        <p className="text-accent text-sm m-0">
          © {year} {title}
        </p>
      </div>
    </footer>
  );
};

export default Footer;
