// vue/src/components/Stack.vue
<template>
  <section v-if="currentStack" id="stack">
    <div class="container-regular">
      <h2 v-if="section.title" class="h2 mb-s">{{ section.title }}</h2>

      <div class="card card--fx mt-m">
        <div class="grid gap-l items-start md:grid-cols-[1.2fr_0.8fr]">
          <!-- Left: summary + list -->
          <div>
            <PortableText v-if="currentStack.summary" :value="currentStack.summary" />

            <ul
              v-if="currentStack.list?.length"
              class="mt-xs pl-l list-disc list-outside space-y-2xs"
            >
              <li v-for="(item, index) in currentStack.list" :key="`${item}-${index}`">
                {{ item }}
              </li>
            </ul>
          </div>

          <!-- Right: stack switcher buttons -->
          <div class="flex flex-col" role="group" :aria-label="switcherLabel">
            <p v-if="section.tryStack" class="text-muted">{{ section.tryStack }}</p>

            <div class="flex flex-wrap gap-s mt-xs">
              <template v-for="(stack, index) in section.stacks" :key="`${stack.host}-${index}`">
                <Button
                  v-if="stack.host && stack.label"
                  :href="`https://${stack.host}`"
                  target="_self"
                  rel="noopener noreferrer"
                >
                  {{ stack.label }}
                </Button>
              </template>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { StackSection, StringsDoc } from '../types'
import { selectStackVariant } from '../utils/stackHelpers'
import Button from './ui/Button.vue'
import PortableText from './ui/PortableText.vue'

const props = defineProps<{
  section: StackSection
  strings?: StringsDoc | null
}>()

const currentStack = computed(() => selectStackVariant(props.section.stacks, 'Vue'))
const switcherLabel = computed(() => props.strings?.stackSwitcherLabel ?? 'Stack demos')
</script>

// react/src/components/Stack.tsx
import type { FC } from 'react';
import type { StackSection as StackSectionData, StringsDoc } from '../types';
import { SanityPortableText } from '../sanity/SanityPortableText';
import { Button } from './ui/Button';

type StackProps = {
  section: StackSectionData;
  strings?: StringsDoc | null;
};

export const Stack: FC<StackProps> = ({ section, strings }) => {
  const { title, tryStack, stacks = [] } = section;
  if (!stacks.length) return null;

  const currentStack =
    stacks.find((s) => s.label?.toLowerCase().includes('react')) ?? stacks[0];

  const switcherLabel =
    strings?.stackSwitcherLabel ?? 'Stack demos';

  return (
    <section id="stack">
      <div>
        {title && <h2 className="h2 mb-s">{title}</h2>}

        <div className="card card--fx mt-m">
          <div className="grid gap-l items-start md:grid-cols-[1.2fr_0.8fr]">
            <div>
              {currentStack?.summary && (
                <SanityPortableText value={currentStack.summary} />
              )}

              {currentStack?.list?.length ? (
                <ul className="mt-xs pl-l list-disc list-outside space-y-2xs">
                  {currentStack.list.map((item, index) => (
                    <li key={`${item}-${index}`}>{item}</li>
                  ))}
                </ul>
              ) : null}
            </div>

            <div
              className="flex flex-col"
              role="group"
              aria-label={switcherLabel}
            >
              {tryStack && (
                <p className="text-muted">
                  {tryStack}
                </p>
              )}

              <div className="flex flex-wrap gap-s mt-xs">
                {stacks.map((stack, index) => {
                  const { host, label } = stack || {};
                  if (!host || !label) return null;

                  return (
                    <Button
                      key={`${host}-${index}`}
                      href={`https://${host}`}
                      variant="default"
                      target="_self"
                      rel="noopener noreferrer"
                    >
                      {label}
                    </Button>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Stack;
